<a href="https://colab.research.google.com/github/JMC110/Ungraded-Assignment-4-DLPyTorchBook-/blob/master/chapter%202/1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
a = [1.0, 5.0, 1.0]

In [2]:
a[0]

1.0

In [4]:
a[2] = 3.0
a

[1.0, 5.0, 3.0]

In [5]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [0]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [10]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points.shape

torch.Size([3, 2])

In [15]:
points = torch.zeros(3, 4)
points

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points[0, 1]

tensor(1.)

In [18]:
points[0]

tensor([4., 1.])

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [20]:
points_storage = points.storage()
points_storage[3]

3.0

In [21]:
points.storage()[1]

1.0

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[2]
second_point.storage_offset()

4

In [25]:
second_point.size()

torch.Size([2])

In [26]:
second_point.shape

torch.Size([2])

In [27]:
points.stride()

(2, 1)

In [28]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [29]:
second_point.storage_offset()

2

In [30]:
second_point.stride()

(1,)

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [33]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [35]:
points_tens = points.t()
points_tens

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [36]:
id(points.storage()) == id(points_t.storage())

True

In [37]:
points.stride()

(2, 1)

In [38]:
points_t.stride()

(1, 2)

In [39]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [40]:
transpose_t.shape

torch.Size([5, 4, 3])

In [41]:
some_t.stride()

(20, 5, 1)

In [42]:
transpose_t.stride()

(1, 5, 20)

In [43]:
points.is_contiguous()

True

In [44]:
points_t.is_contiguous()

False

In [45]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [46]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [48]:
points_tens.stride()

(1, 2)

In [49]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [50]:
points_t_cont.stride()

(3, 1)

In [51]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [53]:
short_points.dtype

torch.int16

In [0]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [0]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [55]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [0]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [57]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [58]:
points[1:]       
points[1:, :]    
points[1:, 0]    
points[None]     

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [59]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [0]:
points = torch.from_numpy(points_np)

In [0]:
torch.save(points, 'ourpoints.t')

In [0]:
with open('ourpoints.t','wb') as f:
   torch.save(points, f)

In [0]:
points = torch.load('ourpoints.t')

In [0]:
with open('ourpoints.t','rb') as f:
   points = torch.load(f)

In [0]:
import h5py

f = h5py.File('ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [0]:
f = h5py.File('ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [0]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [0]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [0]:
points_gpu = points.to(device='cuda')

In [0]:
points_gpu = points.to(device='cuda:0')

In [0]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [0]:
points_gpu = points_gpu + 4


In [0]:
points_cpu = points_gpu.to(device='cpu')


In [0]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [75]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [76]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [0]:
a = torch.ones(3, 2)

In [78]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])